export const integrationEnv = {
  uglybot: 'UGLYBOT_DATABASE_URL',
  prizes: 'UGLYBOT_PRIZES_DATABASE_URL',
  claims: 'UGLYBOT_CLAIMS_DATABASE_URL',
  points: 'UGLYBOT_POINTS_DATABASE_URL',
  gauntlet: 'GAUNTLET_DATABASE_URL',
  survival: 'GAUNTLET_SURVIVAL_DATABASE_URL',
  images: 'GAUNTLET_IMAGE_DATABASE_URL',
  submissions: 'IMAGE_SUBMIT_DATABASE_URL',
  links: 'WALLET_LINKS_DATABASE_URL',
} as const;
export type Integration = keyof typeof integrationEnv;
export type TableSpec = {
  integration: Integration;
  table: string;
  keys: string[];
  required: string[];
  optional: string[];
};
// Some feeds have no row timestamp: Survival's event date comes from its game.
export function sourceTimestamp(spec: TableSpec) {
  return [
    'submitted_at',
    'added_at',
    'finished_at',
    'used_at',
    'received_at',
    'started_at',
    'created_at',
    'updated_at',
  ].find((column) => spec.required.includes(column));
}
const spec = (
  integration: Integration,
  table: string,
  keys: string[],
  required: string[],
  optional: string[] = [],
): TableSpec => ({
  integration,
  table,
  keys,
  required: [...new Set([...keys, ...required])],
  optional,
});
export const tables = {
  links: spec(
    'links',
    'wallet_links',
    ['guild_id', 'discord_id', 'wallet_address'],
    ['verified'],
    ['created_at', 'updated_at'],
  ),
  duels: spec(
    'uglybot',
    'squig_duels',
    ['id'],
    ['challenger_id', 'opponent_id', 'status', 'created_at'],
    [
      'guild_id',
      'challenger_squig_token_id',
      'opponent_squig_token_id',
      'winner_id',
      'wager_amount',
      'completed_at',
      'updated_at',
    ],
  ),
  rounds: spec(
    'uglybot',
    'squig_duel_rounds',
    ['id'],
    ['duel_id', 'round_number', 'created_at'],
    ['challenger_action', 'opponent_action', 'challenger_hp', 'opponent_hp'],
  ),
  favorites: spec(
    'uglybot',
    'squig_duel_player_squigs',
    ['guild_id', 'user_id', 'token_id'],
    ['nickname', 'is_favorite'],
    ['updated_at'],
  ),
  marketplace: spec(
    'prizes',
    'malformed_marketplace_purchases',
    ['id'],
    ['user_id', 'status', 'created_at'],
    [
      'guild_id',
      'item_key',
      'item_name',
      'price',
      'delivered_at',
      'updated_at',
    ],
  ),
  purchases: spec(
    'prizes',
    'marketplace_purchases',
    ['id'],
    ['discord_id', 'created_at', 'spent_amount'],
    ['item_id', 'quantity', 'purchase_type', 'refunded_amount', 'refunded_at'],
  ),
  bounty: spec(
    'prizes',
    'bounty_submissions',
    ['id'],
    ['sender_discord_id', 'created_at', 'status'],
    [
      'guild_id',
      'chain',
      'contract_address',
      'token_id',
      'yes_votes',
      'no_votes',
      'accepted_at',
      'charm_payout_status',
      'project_name',
      'rejected_at',
      'updated_at',
    ],
  ),
  bountyResults: spec(
    'prizes',
    'bounty_draw_results',
    ['id'],
    ['winner_discord_id', 'created_at'],
    [
      'draw_id',
      'winning_entry_token_id',
      'winning_entry_contract',
      'charm_amount',
      'payout_status',
      'delivery_status',
      'winner_wallet',
      'bounty_submission_id',
      'prize_type',
      'revealed_at',
      'delivered_at',
    ],
  ),
  maw: spec(
    'prizes',
    'maw_return_sessions',
    ['id'],
    [
      'discord_user_id',
      'contract_address',
      'token_id',
      'received_at',
      'status',
    ],
    [
      'event_id',
      'payout_amount',
      'payout_status',
      'rarity_tier',
      'reward_rules_version',
      'squig_disposition',
      'updated_at',
      'created_at',
      'received_tx_hash',
      'overall_rank',
      'ticket_count',
      'jackpot_contribution_charm',
      'digestion_status',
      'burn_transaction_hash',
      'burn_confirmed_at',
    ],
  ),
  madlibs: spec(
    'prizes',
    'madlib_sessions',
    ['id'],
    ['user_id', 'state', 'created_at'],
    ['template_id', 'completed_at', 'cost'],
  ),
  claimEvents: spec(
    'claims',
    'claim_events',
    ['id'],
    ['discord_id', 'created_at', 'amount'],
    ['guild_id', 'nft_count', 'payout_type'],
  ),
  claimNfts: spec(
    'claims',
    'nft_claims',
    ['guild_id', 'chain', 'contract_address', 'token_id'],
    ['last_claimed_at'],
    ['last_seen_owner_wallet', 'last_seen_discord_id', 'last_payout_amount'],
  ),
  pointMappings: spec(
    'points',
    'holder_point_mappings',
    ['guild_id', 'chain', 'contract_address'],
    [],
    ['created_by_discord_id'],
  ),
  runs: spec(
    'gauntlet',
    'gauntlet_runs',
    ['id'],
    ['user_id', 'score', 'finished_at'],
    ['result_type', 'final_round', 'max_greed_level'],
  ),
  onlineRewards: spec(
    'gauntlet',
    'gauntlet_online_reward_events',
    ['event_id'],
    ['discord_user_id', 'amount', 'status', 'created_at'],
    ['run_id', 'processed_at'],
  ),
  games: spec('survival', 'squig_survival_games', ['id'], ['started_at']),
  survival: spec(
    'survival',
    'squig_survival_game_players',
    ['game_id', 'user_id'],
    ['eliminations', 'deaths', 'images_used', 'placement'],
  ),
  joins: spec(
    'survival',
    'squig_survival_game_joins',
    ['id'],
    ['game_id', 'user_id', 'joined_at'],
  ),
  imageUses: spec(
    'survival',
    'squig_survival_image_uses',
    ['id'],
    ['game_id', 'user_id', 'image_url', 'used_at'],
  ),
  liveImages: spec(
    'images',
    'squig_survival_images',
    ['id'],
    ['user_id', 'image_url', 'created_at'],
    ['era_keys', 'reward_points', 'milestone_key', 'milestone_number'],
  ),
  notifications: spec(
    'images',
    'squig_survival_image_approval_notifications',
    ['id'],
    ['discord_user_id', 'approved_at'],
    ['submission_id', 'reward_points', 'post_status'],
  ),
  submissions: spec(
    'submissions',
    'squig_survival_image_submissions',
    ['id'],
    ['discord_user_id', 'status', 'submitted_at'],
    [
      'reviewed_at',
      'era_key',
      'reward_points',
      'milestone_key',
      'milestone_number',
      'live_image_id',
      'image_url',
      'milestone_label',
      'row_version',
    ],
  ),
  bountyEntries: spec(
    'prizes',
    'bounty_pool_entries',
    ['id'],
    ['chain', 'contract_address', 'token_id', 'added_at', 'status'],
    ['month_key', 'removed_at'],
  ),
  madlibPublications: spec(
    'prizes',
    'madlib_publications',
    ['id'],
    ['user_id', 'status', 'created_at'],
    ['updated_at', 'suspended'],
  ),
  madlibOperations: spec(
    'prizes',
    'madlib_operations',
    ['id'],
    ['user_id', 'kind', 'state', 'amount', 'currency_id', 'created_at'],
    ['updated_at', 'confirmed_at'],
  ),
  mawPrizes: spec(
    'prizes',
    'maw_squig_pool',
    ['id'],
    ['contract_address', 'token_id', 'status', 'updated_at'],
    ['delivered_to_discord_id', 'delivered_tx_hash', 'rarity_tier'],
  ),
} satisfies Record<string, TableSpec>;
